#!/usr/bin/env python3
"""Audit Pixtee's *planned* art sizes, file IDs, and actual imported PNGs.

A passing manifest schema is NOT art approval. If production image bytes exist,
they must have owner signoff + SHA-256 in ART_REVIEW_REGISTER.json. No images
are copied/generated by this script. The required 256x128 golfer frame is a
forward-looking export target, and currently requires a Pixtee renderer upgrade.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import re
import struct
import sys

ROOT = Path(__file__).resolve().parents[1]
PLAN = ROOT / "spec/pixtee/ASTRA_ART_EXPORT_MANIFEST_v1.json"
BIBLE = ROOT / "spec/pixtee/ASTRA_FINAL_ART_ASSET_BIBLE_2026-10-10.md"
APPROVAL = ROOT / "spec/pixtee/ART_REVIEW_REGISTER.json"
CONTRACT = ROOT / "pixtee-android/app/src/main/java/com/pixtee/golf/ProductionPixelArt.kt"
RESOLUTION = ROOT / "spec/pixtee/SCREEN_RESOLUTION_AND_WORLD_SCALE_2026-10-10.json"

def require(ok: bool, message: str) -> None:
    if not ok:
        raise AssertionError(message)

def png_size(path: Path) -> tuple[int,int]:
    with path.open("rb") as f:
        b = f.read(24)
    require(len(b) >= 24 and b[:8] == b"\x89PNG\r\n\x1a\n"
            and b[12:16] == b"IHDR", f"not valid PNG {path}")
    return struct.unpack(">II", b[16:24])

def code_ids(text: str) -> set[str]:
    found = set()
    for name in ("TERRAIN_TILES", "UI_ART", "REQUIRED_SPRITES"):
        match = re.search(r"val\s+" + name +
            r":\s*List<String>\s*=\s*listOf\(([\s\S]*?)\)", text)
        require(match is not None, f"cannot find Kotlin asset list: {name}")
        rows = re.findall(r'"([^"]+)"', match.group(1))
        require(len(rows) == len(set(rows)), "duplicate Kotlin asset key in " + name)
        found.update(rows)
    return found

def main() -> None:
    data=json.loads(PLAN.read_text())
    approval=json.loads(APPROVAL.read_text())
    source=json.loads(CONTRACT.read_text()) if False else CONTRACT.read_text()
    guide=BIBLE.read_text()
    numbers=json.loads(RESOLUTION.read_text())
    require(data["schema"]=="pixtee.art.export-plan.v1", "invalid manifest schema")
    require(data["status"]=="PLANNED_SIZES_NOT_APPROVED","cannot mark plan as approved")
    original=data["original_game_measured"]
    require((original["world_width"],original["world_height"])==(544,912),
            "original reference world dimensions changed")
    require((original["collision_cell_world_width"],original["collision_cell_world_height"])==(2,2),
            "original MAPI fine collision cell changed")
    require(original["verified_mch_frames"]==874, "original MCH source frame count changed")
    require(numbers["original_game"]["main_world_units"]==[544,912],
            "source-verified world reference mismatches scaling contract")
    require(numbers["original_game"]["collision_cell_world_units"]==[2,2],
            "source-verified collision reference mismatches scaling contract")

    g=data["pixtee_proposed_final"]["golfer"]
    density=data["pixtee_proposed_final"]["art_pixels_per_world"]
    require(density==8, "Pixtee final art density changed without new contract")
    require(g["frame_px"]==[256,128] and g["feet_pivot_px"]==[80,116]
            and g["impact_contact_px"]==[108,116], "golfer dimensions/pivots changed")
    require(g["world_padded_wh"] == [g["frame_px"][0]/density,
            g["frame_px"][1]/density], "frame world footprint changed")
    require((g["impact_contact_px"][0]-g["feet_pivot_px"][0])/density == 3.5
            and g["impact_contact_px"][1]==g["feet_pivot_px"][1],
            "contact cannot meet physical ball at 3.5 world offset")
    require(data["pixtee_proposed_final"]["terrain_tile"]["source_px"]==[128,64],
            "tile export changes 16x8 world-size template")
    require(data["pixtee_proposed_final"]["terrain_tile"]["world_wh"]==[16,8],
            "original-world tile unit size changed")
    require(data["pixtee_proposed_final"]["sponsor_sign"]["source_px"]==[352,160],
            "current world sign RectF no longer matches art dimensions")

    rows=data["assets"]
    require(len(rows)==31 and data["asset_count"]==31, "baseline loader must have 31 IDs")
    ids={r["id"] for r in rows}
    require(len(ids)==len(rows), "duplicate registered IDs")
    require(ids==code_ids(source),
            f"manifest vs Kotlin production loader IDs drift: missing={code_ids(source)-ids}, extra={ids-code_ids(source)}")

    existing_approvals={}
    for row in approval["approvedAssets"]:
        fn=Path(row["file"]).name
        require(fn not in existing_approvals, "duplicate owner approval")
        existing_approvals[fn]=row

    existing_review=existing_production=0
    for item in rows:
        id=item["id"]
        size=(item["export_pixels"]["width"],item["export_pixels"]["height"])
        require(all(isinstance(n,int) and n>0 for n in size), f"{id}: invalid export size")
        require(item["filename"]==id+".png", f"{id}: incorrect filename")
        require(item["runtime_path"] ==
            f"pixtee-android/app/src/main/assets/art/production/{id}.png",
            f"{id}: app will not find production art at intended path")
        require(item["review_path"] ==
            f"pixtee-android/app/src/main/assets/art/review/{id}.png",
            f"{id}: review path not wired to loader")
        require(item["contract"]=="PIXTEE_PROPOSED_FINAL_NOT_VERIFIED_OR_APPROVED",
            f"{id}: unverified export size falsely marked approved")
        require(f"`{id}.png`" in guide, f"asset missing from Astra MD: {id}")
        if item["category"]=="golfer":
            require(size==(256,128), f"golfer frame isn't 256x128: {id}")
        if item["category"]=="terrain":
            require(size==(128,64), f"terrain tile isn't 128x64: {id}")

        for placement in ("review_path", "runtime_path"):
            file=ROOT/item[placement]
            if not file.exists(): continue
            require(png_size(file)==size,
                f"{id}: PNG measured {png_size(file)} != contracted {size}")
            if placement=="review_path":
                existing_review+=1
            else:
                existing_production+=1
                signed=existing_approvals.get(file.name)
                require(signed is not None,
                    f"{id}: production PNG has NO owner approval register entry")
                digest=hashlib.sha256(file.read_bytes()).hexdigest()
                require(signed.get("sha256")==digest and
                    bool(signed.get("ownerApprovalReference")),
                    f"{id}: approval lacks matching SHA256 or owner reference")

    marker=ROOT/"pixtee-android/app/src/main/assets/art/production/APPROVED_v1.txt"
    if marker.exists():
        require(marker.read_text().strip()=="PIXTEE_PRODUCTION_ART_APPROVED_V1",
                "incorrect production approval marker")
        require(existing_production==31,
                "production approval marker present before all core assets exist")
    print(f"PASS: 31/31 art IDs, exact proposed export dimensions, 544x912 "
          f"source-world / 2x2 terrain resolution, contact/pivots and save paths.")
    print(f"STATUS: review images present {existing_review}/31; owner-approved production "
          f"images present {existing_production}/31; source-size parity + final "
          "art review remain separate and PENDING.")
    if "FRAME_PX_W = 128" in (ROOT/"pixtee-android/app/src/main/java/com/pixtee/golf/PixteeSwingRig.kt").read_text():
        print("BLOCKER: current renderer STILL requires 128x64 golfer PNGs; "
              "Astra must upgrade it to 256x128 / (80,116),(108,116) before "
              "importing approved final golfer art.")

if __name__=="__main__":
    try:
        main()
    except (OSError,ValueError,KeyError,AssertionError) as exc:
        sys.exit(f"FAIL Pixtee art source/geometry/size contract: {exc}")
